
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter:
  host:
  encoding:
  database:
  username:
  password:
  pool: 5
  timeout: 5000
